# Generated by Django 5.2.6 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='title',
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(default='core/assets/img/default.jpg', upload_to='characters/'),
        ),
    ]
