# Generated by Django 5.2.6 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='img',
            field=models.ImageField(default='core/assets/img/default.jpg', upload_to='comics/'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
