# Generated by Django 5.2.6 on 2025-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_comic_description_alter_comic_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
