# Generated by Django 5.2.6 on 2025-10-05 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='core/assets/img/default.jpg', upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
